### ISSUE TITLE
Tickers before 2016

### ISSUE THREAD

**Issue by aptperson** [jmccarrell/n100tickers#12]
Hi, 

Amazing work on this library.

Quick question. How come you don't have tickers pre 2016. Is the Wikipedia entry unreliable prior to this date?

**Comment by jmccarrell** [comment]
> Amazing work on this library.

Thanks!

I do have a branch for 2015; the last commit message I wrote there says:

> there are issues with the data that make this non-obvious.

and I remember thinking that adding another year of history wasn't worth the effort.
